# main.tf -- generated by pipeline-automator scaffold (project init)
# CI/CD identities for payroll_pipeline_2026_09_17, as code: one GitHub OIDC provider and three
# least-privilege roles, federated-trusted per role so a workflow can only assume the
# role its job actually needs.
#   plan    -- read-only; runs on every push and pull_request.
#   deploy  -- creates/updates the main stack's resources; runs only on push to
#              main, and only from a job bound to the
#              GitHub `dev` Environment (its Required
#              reviewers rule is what actually gates the apply -- this trust policy only
#              ensures the role can't be assumed outside that Environment).
#   scripts -- uploads the shared library zip and job scripts to S3; no Terraform, no
#              state access; runs only on push to main.
# No long-lived AWS credentials are ever stored in GitHub -- every role is assumed via
# OIDC's sts:AssumeRoleWithWebIdentity.

locals {
  name_prefix             = "${var.data_product}-${var.environment}"
  name_prefix_underscored = replace(local.name_prefix, "-", "_")
  state_object_arn        = "arn:aws:s3:::${var.tfstate_bucket}/${var.data_product}/terraform.tfstate"
  # Terraform's S3-native lock (`use_lockfile = true`, see ../providers.tf.j2) is a
  # conditional-write object at the state key plus a ".tflock" suffix -- not a separate
  # DynamoDB table, so both roles' state permissions must cover this object too.
  lock_object_arn = "${local.state_object_arn}.tflock"
}

data "aws_caller_identity" "current" {}

data "tls_certificate" "github_actions" {
  url = "https://token.actions.githubusercontent.com/.well-known/openid-configuration"
}

resource "aws_iam_openid_connect_provider" "github_actions" {
  url             = "https://token.actions.githubusercontent.com"
  client_id_list  = ["sts.amazonaws.com"]
  thumbprint_list = [data.tls_certificate.github_actions.certificates[0].sha1_fingerprint]
}

# ---------------------------------------------------------------------------
# plan -- read-only, both push and pull_request contexts
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "plan_assume" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    principals {
      type        = "Federated"
      identifiers = [aws_iam_openid_connect_provider.github_actions.arn]
    }
    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:aud"
      values   = ["sts.amazonaws.com"]
    }
    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:sub"
      values = [
        "repo:${var.github_owner_repo}:pull_request",
        "repo:${var.github_owner_repo}:ref:refs/heads/${var.default_branch}",
      ]
    }
  }
}

resource "aws_iam_role" "plan" {
  name               = "${local.name_prefix}-cicd-plan"
  assume_role_policy = data.aws_iam_policy_document.plan_assume.json
}

# Read-only on the resource types the main stack manages, plus state access. No wildcard
# admin (e.g. no iam:List* with resource "*") beyond the handful of List/Describe actions
# AWS defines as account-wide and does not support resource-level scoping for.
data "aws_iam_policy_document" "plan_permissions" {
  statement {
    sid    = "S3ReadOnly"
    effect = "Allow"
    actions = [
      "s3:GetBucket*",
      "s3:GetEncryptionConfiguration",
      "s3:GetLifecycleConfiguration",
      "s3:GetBucketPolicy",
      "s3:ListBucket",
    ]
    resources = ["arn:aws:s3:::${local.name_prefix}-*"]
  }

  statement {
    sid       = "S3ListAllBuckets"
    effect    = "Allow"
    actions   = ["s3:ListAllMyBuckets"]
    resources = ["*"] # AWS does not support resource-level scoping for this action.
  }

  statement {
    sid    = "IAMReadOnly"
    effect = "Allow"
    actions = [
      "iam:GetRole",
      "iam:GetPolicy",
      "iam:GetPolicyVersion",
      "iam:ListRolePolicies",
      "iam:ListAttachedRolePolicies",
      "iam:ListPolicyVersions",
    ]
    resources = [
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.name_prefix}-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/${local.name_prefix}-*",
    ]
  }

  statement {
    sid    = "GlueAndAthenaReadOnly"
    effect = "Allow"
    actions = [
      "glue:GetDatabase",
      "glue:GetDatabases",
      "glue:GetTable",
      "glue:GetTables",
      "glue:GetJob",
      "glue:GetJobs",
      "athena:GetWorkGroup",
    ]
    resources = concat(
      [
        "arn:aws:glue:${var.aws_region}:${data.aws_caller_identity.current.account_id}:catalog",
        "arn:aws:glue:${var.aws_region}:${data.aws_caller_identity.current.account_id}:database/${local.name_prefix_underscored}_*",
        "arn:aws:glue:${var.aws_region}:${data.aws_caller_identity.current.account_id}:table/${local.name_prefix_underscored}_*/*",
        "arn:aws:glue:${var.aws_region}:${data.aws_caller_identity.current.account_id}:job/${local.name_prefix}-*",
      ],
      ["arn:aws:athena:${var.aws_region}:${data.aws_caller_identity.current.account_id}:workgroup/${local.name_prefix}-catalog"],
    )
  }

  statement {
    sid       = "TerraformStateAccess"
    effect    = "Allow"
    actions   = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject"]
    resources = [local.state_object_arn, local.lock_object_arn]
  }
}

resource "aws_iam_policy" "plan" {
  name   = "${local.name_prefix}-cicd-plan-policy"
  policy = data.aws_iam_policy_document.plan_permissions.json
}

resource "aws_iam_role_policy_attachment" "plan" {
  role       = aws_iam_role.plan.name
  policy_arn = aws_iam_policy.plan.arn
}

# ---------------------------------------------------------------------------
# deploy -- create/update/delete, only from a job bound to the prod Environment
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "deploy_assume" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    principals {
      type        = "Federated"
      identifiers = [aws_iam_openid_connect_provider.github_actions.arn]
    }
    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:aud"
      values   = ["sts.amazonaws.com"]
    }
    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:sub"
      values   = ["repo:${var.github_owner_repo}:environment:${var.environment}"]
    }
  }
}

resource "aws_iam_role" "deploy" {
  name               = "${local.name_prefix}-cicd-deploy"
  assume_role_policy = data.aws_iam_policy_document.deploy_assume.json
}

# Create/update/delete on exactly the resource types the main stack provisions,
# scoped by name_prefix -- never "*". This role applies the main stack, so it must not
# be created by that stack (that's why it lives in this separate bootstrap root/state).
data "aws_iam_policy_document" "deploy_permissions" {
  statement {
    sid    = "S3BucketManage"
    effect = "Allow"
    actions = [
      "s3:CreateBucket",
      "s3:DeleteBucket",
      "s3:PutBucketVersioning",
      "s3:PutBucketTagging",
      "s3:PutEncryptionConfiguration",
      "s3:PutBucketPublicAccessBlock",
      "s3:PutLifecycleConfiguration",
      "s3:GetBucket*",
      "s3:GetEncryptionConfiguration",
      "s3:GetLifecycleConfiguration",
      "s3:GetBucketPolicy",
      "s3:ListBucket",
    ]
    resources = ["arn:aws:s3:::${local.name_prefix}-*"]
  }

  # Attaching AWSGlueServiceRole (the Glue execution role's one AWS-managed attachment,
  # see modules/iam/main.tf.j2) needs its ARN alongside the name_prefix-scoped roles this
  # role otherwise manages.
  statement {
    sid    = "IAMManage"
    effect = "Allow"
    actions = [
      "iam:CreateRole",
      "iam:DeleteRole",
      "iam:GetRole",
      "iam:TagRole",
      "iam:UntagRole",
      "iam:CreatePolicy",
      "iam:DeletePolicy",
      "iam:CreatePolicyVersion",
      "iam:DeletePolicyVersion",
      "iam:GetPolicy",
      "iam:GetPolicyVersion",
      "iam:ListPolicyVersions",
      "iam:AttachRolePolicy",
      "iam:DetachRolePolicy",
      "iam:PutRolePolicy",
      "iam:DeleteRolePolicy",
      "iam:ListRolePolicies",
      "iam:ListAttachedRolePolicies",
      "iam:PassRole",
    ]
    resources = [
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/${local.name_prefix}-*",
      "arn:aws:iam::${data.aws_caller_identity.current.account_id}:policy/${local.name_prefix}-*",
      "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole",
    ]
  }

  statement {
    sid    = "GlueJobsManage"
    effect = "Allow"
    actions = [
      "glue:CreateJob",
      "glue:UpdateJob",
      "glue:DeleteJob",
      "glue:GetJob",
      "glue:GetJobs",
      "glue:TagResource",
      "glue:UntagResource",
    ]
    resources = ["arn:aws:glue:${var.aws_region}:${data.aws_caller_identity.current.account_id}:job/${local.name_prefix}-*"]
  }

  # glue:CreateTable is deliberately absent, mirroring modules/iam/main.tf.j2's own
  # execution-role policy: no identity in this project is meant to create Iceberg tables
  # except `make catalog-apply`, under its own separate deployer identity.
  statement {
    sid    = "GlueCatalogManage"
    effect = "Allow"
    actions = [
      "glue:CreateDatabase",
      "glue:UpdateDatabase",
      "glue:DeleteDatabase",
      "glue:GetDatabase",
      "glue:GetDatabases",
      "glue:TagResource",
    ]
    resources = [
      "arn:aws:glue:${var.aws_region}:${data.aws_caller_identity.current.account_id}:catalog",
      "arn:aws:glue:${var.aws_region}:${data.aws_caller_identity.current.account_id}:database/${local.name_prefix_underscored}_*",
    ]
  }

  statement {
    sid    = "AthenaWorkgroupManage"
    effect = "Allow"
    actions = [
      "athena:CreateWorkGroup",
      "athena:UpdateWorkGroup",
      "athena:DeleteWorkGroup",
      "athena:GetWorkGroup",
      "athena:TagResource",
    ]
    resources = ["arn:aws:athena:${var.aws_region}:${data.aws_caller_identity.current.account_id}:workgroup/${local.name_prefix}-catalog"]
  }

  statement {
    sid       = "TerraformStateAccess"
    effect    = "Allow"
    actions   = ["s3:GetObject", "s3:PutObject", "s3:DeleteObject"]
    resources = [local.state_object_arn, local.lock_object_arn]
  }
}

resource "aws_iam_policy" "deploy" {
  name   = "${local.name_prefix}-cicd-deploy-policy"
  policy = data.aws_iam_policy_document.deploy_permissions.json
}

resource "aws_iam_role_policy_attachment" "deploy" {
  role       = aws_iam_role.deploy.name
  policy_arn = aws_iam_policy.deploy.arn
}

# ---------------------------------------------------------------------------
# scripts -- upload the shared library zip and job scripts; no Terraform, no state
# ---------------------------------------------------------------------------

data "aws_iam_policy_document" "scripts_assume" {
  statement {
    actions = ["sts:AssumeRoleWithWebIdentity"]
    principals {
      type        = "Federated"
      identifiers = [aws_iam_openid_connect_provider.github_actions.arn]
    }
    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:aud"
      values   = ["sts.amazonaws.com"]
    }
    condition {
      test     = "StringEquals"
      variable = "token.actions.githubusercontent.com:sub"
      values   = ["repo:${var.github_owner_repo}:ref:refs/heads/${var.default_branch}"]
    }
  }
}

resource "aws_iam_role" "scripts" {
  name               = "${local.name_prefix}-cicd-scripts"
  assume_role_policy = data.aws_iam_policy_document.scripts_assume.json
}

data "aws_iam_policy_document" "scripts_permissions" {
  statement {
    sid       = "ScriptsBucketUpload"
    effect    = "Allow"
    actions   = ["s3:PutObject", "s3:ListBucket"]
    resources = [var.scripts_bucket_arn, "${var.scripts_bucket_arn}/*"]
  }
}

resource "aws_iam_policy" "scripts" {
  name   = "${local.name_prefix}-cicd-scripts-policy"
  policy = data.aws_iam_policy_document.scripts_permissions.json
}

resource "aws_iam_role_policy_attachment" "scripts" {
  role       = aws_iam_role.scripts.name
  policy_arn = aws_iam_policy.scripts.arn
}
