# outputs.tf -- generated by pipeline-automator scaffold (project init)
# The three CI/CD role ARNs -- copy these into the repo secrets named in
# infra/terraform/bootstrap/README.md after every apply.

output "plan_role_arn" {
  description = "ARN of the read-only role CI assumes to run `terraform plan`. Copy into the repo secret AWS_PLAN_ROLE_ARN."
  value       = aws_iam_role.plan.arn
}

output "deploy_role_arn" {
  description = "ARN of the role CI assumes to run `terraform apply`. Copy into the repo secret AWS_DEPLOY_ROLE_ARN."
  value       = aws_iam_role.deploy.arn
}

output "scripts_role_arn" {
  description = "ARN of the role CI assumes to upload the shared library zip and job scripts. Copy into the repo secret AWS_SCRIPTS_ROLE_ARN."
  value       = aws_iam_role.scripts.arn
}
