# providers.tf -- generated by pipeline-automator scaffold (project init)
# Bootstrap provider and backend configuration for payroll_pipeline_2026_09_17's CI/CD OIDC
# roles. This root is applied once, by an admin, from its own state file, distinct
# from the main stack's -- the deploy role provisioned here is what applies the main
# stack, so it must never be created by the stack it applies.

terraform {
  required_version = ">= 1.10.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }

  backend "s3" {
    bucket       = "payroll-pipeline-tfstate-bucket"
    key          = "payroll_pipeline_2026_09_17/bootstrap/terraform.tfstate"
    region       = "eu-central-1"
    use_lockfile = true
    encrypt      = true
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      DataProduct = "payroll_pipeline_2026_09_17"
      ManagedBy   = "terraform"
      Project     = "payroll_pipeline_2026_09_17"
      Component   = "cicd-bootstrap"
    }
  }
}
