# variables.tf -- generated by pipeline-automator scaffold (project init)
# Bootstrap-root input variables for payroll_pipeline_2026_09_17's CI/CD OIDC roles.

variable "aws_region" {
  description = "AWS region the CI/CD IAM roles and OIDC provider are created in."
  type        = string
  default     = "eu-west-1"
}

variable "data_product" {
  description = "Name of the data product these CI/CD roles belong to."
  type        = string
  default     = "payroll_pipeline_2026_09_17"
}

variable "environment" {
  description = "Deployment environment. Matches the main stack's var.environment, and the GitHub Environment name that gates `terraform apply` in CI -- the deploy role's trust policy is scoped to exactly this Environment."
  type        = string
  default     = "dev"
}

variable "default_branch" {
  description = "The GitHub repository's default branch. Scopes the plan and scripts roles' trust policies to push events on this branch."
  type        = string
  default     = "main"
}

variable "github_owner_repo" {
  description = <<-EOT
    The GitHub repository these roles trust, as "<owner>/<repo>" (e.g. "my-org/my-data-product").
    REQUIRED: the default below is a placeholder, not a real value. Override it at apply
    time (`terraform apply -var="github_owner_repo=<owner>/<repo>"`) -- left unset, every
    role's trust policy scopes to a repository that does not exist, and no workflow run
    will ever be able to assume any of these roles.
  EOT
  type        = string
  default     = "<owner>/<repo>"
}

variable "tfstate_bucket" {
  description = "S3 bucket holding both this bootstrap root's own state and the main stack's state."
  type        = string
  default     = "payroll-pipeline-tfstate-bucket"
}

variable "scripts_bucket_arn" {
  description = <<-EOT
    ARN of the main stack's scripts S3 bucket. Computed here from the same naming
    convention modules/s3 uses (<data_product>-<environment>-scripts) so this root
    never needs to read the main stack's state or outputs. If the main stack's bucket
    names are ever hand-overridden away from that convention, update this default to
    match.
  EOT
  type        = string
  default     = "arn:aws:s3:::payroll_pipeline_2026_09_17-dev-scripts"
}
