# providers.tf -- generated by pipeline-automator scaffold (project init)
# Provider and backend configuration for the payroll_pipeline_2026_09_17 data pipeline.

terraform {
  required_version = ">= 1.10.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    bucket       = "payroll-pipeline-tfstate-bucket"
    key          = "payroll_pipeline_2026_09_17/terraform.tfstate"
    region       = "eu-west-1"
    use_lockfile = true
    encrypt      = true
  }
}

provider "aws" {
  region = var.aws_region

  default_tags {
    tags = {
      DataProduct = "payroll_pipeline_2026_09_17"
      ManagedBy   = "terraform"
      Project     = "payroll_pipeline_2026_09_17"
      Environment = var.environment
    }
  }
}
